"""your message

Revision ID: 245e959647aa
Revises: 24f5b1e85c41
Create Date: 2024-01-10 12:58:51.605258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245e959647aa'
down_revision = '24f5b1e85c41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
